### Obtener todos los categorias 

GET http://localhost:3000/api/categories

### Obtener un categoria por id 

GET http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz    

### Crear un nuevo categoria

POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Salon de eventos",
    "description": "Versátil, elegante y amplio"
}

### Modificar un categoria (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz
Content-Type: application/json

{
    "name": "Club Social",
    "description": "Club de barrio, con campo de futbol y pileta"
}

### Modificar un categoria (PATCH - recurso parcial)

PATCH  http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz
Content-Type: application/json

{
    "description": "Club de barrio, con campo de voley y parrilleros"
}

### Borrar un categoria

DELETE http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz
