### Obtener todos los categorias 

GET http://localhost:3000/api/categories

### Obtener un categoria por id 

GET http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz    

### Crear un nuevo categoria

POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Salon de eventos Avellaneda",
    "description": "El salón de eventos ideal para cualquier ocasión. Versátil, elegante y preparado para hacer de tu evento un momento único. ¡Tu celebración, nuestra pasión!"
}

### Modificar un categoria (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz
Content-Type: application/json

{
    "name": "Club Social",
    "description": "¡Festejá tu cumpleaños a lo grande en nuestro club! Un espacio único con música, diversión y todo lo que necesitás para una noche inolvidable. ¡Vení a celebrar como se debe!"
}

### Modificar un categoria (PATCH - recurso parcial)

PATCH  http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz
Content-Type: application/json

{
    "description": "¡Festejá tu cumple en nuestro club! Además de música y diversión, podés armar un partidito de fútbol y disfrutar de una pileta olimpica con tus amigos. ¡Todo lo que necesitás para una celebración espectacular!"
}

### Borrar un categoria

DELETE http://localhost:3000/api/categories/a02b91bc-3769-4221-beb1-d7a3aeba7daz
