### Obtener todos las ubicaciones 

GET http://localhost:3000/api/locations

### Obtener una ubicacion por id 

GET http://localhost:3000/api/locations/a02b91bc-3754-4221-beb1-d7a3aeba7dad   

### Crear una nueva ubicacion

POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "name": "Salon de eventos Avellaneda",
    "address": "Laprida 245",
    "capacity": "150",
    "description": "El salón de eventos ideal para cualquier ocasión. Versátil, elegante y preparado para hacer de tu evento un momento único. ¡Tu celebración, nuestra pasión!"
}

### Modificar una ubicacion (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/locations/a02b91bc-3754-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Club atletico Alumni",
    "address": "Moreno 2578",
    "capacity": "60",
    "description": "¡Festejá tu cumple en nuestro club! Además de música y diversión, podés armar un partidito de fútbol y disfrutar de la pileta. ¡Todo lo que necesitás para una celebración espectacular!"
}

### Modificar una ubicacion (PATCH - recurso parcial)

PATCH  http://localhost:3000/api/locations/a02b91bc-3754-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "capacity": "55",
    "address": "España 1967"
}

### Borrar una ubicacion

DELETE http://localhost:3000/api/locations/a02b91bc-3754-4221-beb1-d7a3aeba7dad
